# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ognots/fungi
  #repository: ognots/filecoin-cad-cad
  pullPolicy: IfNotPresent #Always

secretName: fungi-credentials
secretKey: secret

coord:
  replicaCount: 1
  generateConfigs:
    enabled: true
  service:
    external:
      type: LoadBalancer
      port: 443
      targetPort: 5292
      # SET ME WHEN USING AWS
      ACM:
      hostname: fungi.kittyhawk.wtf
    internal:
      type: ClusterIP
      port: 5292
      targetPort: 5292
  persistence:
    enabled: true
    coord:
      size: "240Gi"
      storageClassName: gp2
      accessModes:
        - ReadWriteOnce
  nodeSelector: {}
  tolerations: []
  #tolerations:
  #    - key: "worker"
  #      operator: "Equal"
  #      value: "false"
  #      effect: "NoSchedule"
  #    - key: "worker"
  #      operator: "Equal"
  #      value: "false"
  #      effect: "NoExecute"
  affinity: {}
  resources: {}

spore:
  replicaCount: 8
  taskCount: 4
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    requests:
      cpu: 4000m
      memory: 20Gi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext:
  fsGroup: 100

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: false
  runAsUser: 1000
